INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("AG", "1", "Alexandra", "Glodzinski", "ag@ucalgary.ca", "Curicula1!", "30000000");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("BN", "2", "Boma", "Nkwonta", "bn@ucalgary.ca", "Curicula1!", "30000001");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("CO", "3", "Colton", "Osterlund", "co@ucalgary.ca", "Curicula1!", "30000002");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("ES", "4", "Erslan", "Salman", "es@ucalgary.ca", "Curicula1!", "30000003");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("GD", "5", "Greg", "Dekvyatov", "gd@ucalgary.ca", "Curicula1!", "30000004");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("KF", "6", "Kyle", "Friedt", "kf@ucalgary.ca", "Curicula1!", "30000005");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("MP", "7", "Melissa", "Picazo", "mp@ucalgary.ca", "Curicula1!", "30000006");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("JB1", "8", "Jack", "Black", "jjj@ucalgary.ca", "Curicula1!", "30000007");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("EW2", "9", "Emma", "Watson", "eee@ucalgary.ca", "Curicula1!", "30000008");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("CF3", "10", "Collin", "Firth", "ccc@ucalgary.ca", "Curicula1!", "30000009");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("EP4", "11", "Elvis", "Presley", "epepepepe@ucalgary.ca", "Curicula1!", "30000010");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("WP5", "12", "Winnie", "the Pooh", "wtp@ucalgary.ca", "Curicula1!", "30000011");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("JB6", "13", "Justin", "Bieber", "jbjbjbjbjbjbj@ucalgary.ca", "Curicula1!", "30000012");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("LG7", "14", "Lady", "Gaga", "llllll@ucalgary.ca", "Curicula1!", "30000013");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("RD8", "15", "Robert", "De Niro", "rdn@ucalgary.ca", "Curicula1!", "30000014");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("TH9", "16", "Tom", "Hanks", "thhhhhhhh@ucalgary.ca", "Curicula1!", "30000015");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("MM10", "17", "Marillyn", "Monroe", "mmmmmmmm@ucalgary.ca", "Curicula1!", "30000016");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("MS11", "18", "Meryl", "Streep", "mandms@ucalgary.ca", "Curicula1!", "30000017");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("OW12", "19", "Oprah", "Whinfrey", "oprah@ucalgary.ca", "Curicula1!", "30000018");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("HF13", "20", "Harrison", "Ford", "ford@ucalgary.ca", "Curicula1!", "30000019");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("SJ14", "21", "Samuel", "Jackson", "jackson@ucalgary.ca", "Curicula1!", "30000020");
INSERT INTO user (userName, userID, firstName, lastName, email, password, schoolID) VALUES ("AJ15", "22", "Angelina", "Jolie", "ajolie@ucalgary.ca", "Curicula1!", "30000021");