/*engg*/
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "17");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "18");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "19");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "20");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "21");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "22");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "23");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "24");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "25");
INSERT INTO programrelcourse(programID, courseID) VALUES("1", "26");

/*ensf*/
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "1");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "2");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "3");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "4");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "5");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "6");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "7");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "8");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "9");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "10");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "11");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "12");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "13");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "14");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "15");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "16");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "17");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "18");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "19");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "20");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "21");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "22");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "23");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "24");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "25");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "26");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "27");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "28");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "29");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "30");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "31");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "32");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "33");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "34");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "35");
INSERT INTO programrelcourse(programID, courseID) VALUES ("2", "36");